### ISSUE TITLE
Ephemeral State: Setup Choices Inconsistency

### ISSUE THREAD

**Issue by serge-tellene** [certeu/morio#60]
Morio v0.3, running in ephemeral state, offers the choice to either "Use the Setup Wizard" or "Provide a Settings File".

When using the first option, it may happen that the user receives a page saying "Setup completed - This Morio instance has already been set up", which is confusing because contradictory with the options offered on the landing page.

**Comment by joostdecock** [comment]
Thank you for helping us improve Morio by reporting this issue 🙏 

> *When using the first option, it may happen*

You mean it is not _always_ happening? 
If possible, open the browser console and check the API request to see what's going on (you can filter on `/-/api/`)

In general, the UI tends to lack behind a bit to changes made in the UI, but it is unlikely that this exact same issue will be present in 0.4 as there was a bit of an overhaul since we've added preseeding support:

<img width="715" alt="Screenshot 2024-09-18 at 09 41 40" src="https://github.com/user-attachments/assets/6dbd311a-4a2b-4858-a555-6b2d6b869c31">

We'll keep this open to ensure it's resolve in 0.4 which should come out later this month.

**Comment by joostdecock** [comment]
Fixed in 0.4. Closing.
